apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      volumes:
        - name: configmap-volume
          configMap:
            name: env-config
      containers:
      - image: mshah1992/udacity-restapi-user
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL 
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: UDAGRAM_DATABASE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_DATABASE
        - name: UDAGRAM_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_HOST
        - name: UDAGRAM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: UDAGRAM_PASSWORD
        - name: UDAGRAM_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: UDAGRAM_USERNAME
      restartPolicy: Always


